name: Build tokems

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
      - name: Build tokens
        run: |
          npm run build-tokens
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit-message: Update tokens
